WIP
witnet/witnet-radon-js pull request #35
Opened 2020-07-14 16:56 UTC by gabaldon

2020-07-16 08:19 UTC, Tommytrg commented on src/script.ts
> +    }, this.firstType) : this.firstType
```suggestion
    return this.getLastOperator() ? this.operators.reduce((acc, operator) => {
      let outputType = operator.operatorInfo.outputType
      return outputType === OutputType.Same ? acc : outputType
    }, this.firstType) : this.firstType
```

2020-07-16 08:21 UTC, Tommytrg commented on src/utils.ts
> +    case MirArgumentType.Map:
Should this return an empty object `{ }`?

2020-07-16 08:22 UTC, Tommytrg requested changes
Check default value for `map`

2020-07-16 10:44 UTC, Tommytrg commented on src/types.ts
> +  Map = 'map',
Could you add test for Argument with a `map` in `getMarkup`, `getMir` and `getJs`?

2020-07-16 10:45 UTC, Tommytrg requested changes
Add tests for Argument class with `map`

2020-07-22 10:04 UTC, gabaldon commented
duplicated in #38

2020-07-22 10:04 UTC, closed without merging