Disallow unsupported reducers, operators and filters
witnet/witnet-radon-js pull request #42
Opened 2020-08-18 12:39 UTC by aesedepece

These changes derive from these issues:
- https://github.com/witnet/witnet-rust/issues/1458
- https://github.com/witnet/witnet-rust/issues/1459

2020-08-18 12:41 UTC, aesedepece commented
This is missing fixing the tests.

2020-08-24 08:46 UTC, aesedepece commented
This is ready for review

2020-08-26 08:56 UTC, Tommytrg approved these changes

2020-08-28 08:52 UTC, mariocao requested changes

2020-08-28 08:52 UTC, mariocao commented on src/utils.ts
> +      return [Filter.deviationStandard, 0]
```suggestion
      return [Filter.deviationStandard, 1.1]
```

2021-02-09 08:55 UTC, aesedepece commented
Updated with @mariocao's suggestion!

2021-02-11 16:57 UTC, mariocao approved these changes

2021-02-12 13:28 UTC, merged