fix: try to parse map arguments and handle error
witnet/witnet-radon-js pull request #43
Opened 2020-08-18 13:36 UTC by Tommytrg

2020-08-18 13:53 UTC, gabaldon requested changes

2020-08-18 13:53 UTC, gabaldon commented on dist/src/argument.js
> +            console.log('+++', this.argumentInfo.type);
Please delete this console.log

2020-08-24 08:45 UTC, gabaldon approved these changes

2020-08-24 08:46 UTC, aesedepece commented on dist/src/argument.js
> +            console.log('+++', this.argumentInfo.type);
It's still there :stuck_out_tongue:

2020-08-24 09:10 UTC, merged