feat: add http-post support
witnet/witnet-radon-js pull request #85
Opened 2022-07-27 16:12 UTC by Tommytrg

2022-07-27 19:17 UTC, aesedepece commented
Please take into account that HTTP-POST requests, in addition to the `headers` field, also have a `body` field (e.g. that's where you'd put a GraphQL query) :wink:

2022-08-01 14:12 UTC, gabaldon commented on src/constants.ts
>  export const KIND_OPTIONS = [Kind.HttpGet, Kind.RNG]
You should add `Kind.HttpPost` to KIND_OPTIONS
```suggestion
export const KIND_OPTIONS = [Kind.HttpGet, Kind.RNG, Kind.HttpPost]
```

2022-08-01 17:09 UTC, gabaldon requested changes
You need to add support for post sources in `radon.ts` constructor.
`this._sourceType = radRequest.retrieve.find((source) => source.kind === Kind.RNG)
      ? Kind.RNG
      : Kind.HttpGet`
This line unable updating the source type to Kind.HttpPost.

2022-08-01 17:40 UTC, gabaldon commented on src/source.ts
> +import { OutgoingHttpHeaders } from 'http'
You need to add `body` and `headers` to the update function, otherwise it will not update.

2022-08-03 16:34 UTC, merged